// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var $$Image = {};

function setFillStyleRGBA(context, r, g, b, a) {
  var value = "rgba(" + r.toString() + "," + g.toString() + "," + b.toString() + "," + a.toString() + ")";
  context.fillStyle = value;
  
}

var Context2d = {
  setFillStyleRGBA: setFillStyleRGBA
};

function createCanvasElement($$document) {
  return $$document.createElement("canvas");
}

var $$Document = {
  createCanvasElement: createCanvasElement
};

function make(width, height) {
  var canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  return canvas;
}

function getContext2d(canvas) {
  return canvas.getContext("2d");
}

function getContext2dWithAlpha(canvas) {
  return canvas.getContext("2d", {
              alpha: true
            });
}

function toDataUrlAsPng(canvas) {
  return canvas.toDataURL("image/png");
}

var Canvas = {
  make: make,
  getContext2d: getContext2d,
  getContext2dWithAlpha: getContext2dWithAlpha,
  toDataUrlAsPng: toDataUrlAsPng
};

var $$File = {};

var $$FileReader = {};

exports.$$Image = $$Image;
exports.Context2d = Context2d;
exports.$$Document = $$Document;
exports.Canvas = Canvas;
exports.$$File = $$File;
exports.$$FileReader = $$FileReader;
/* No side effect */
