// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var MinecraftBlock_Face = require("./MinecraftBlock_Face.bs.js");
var MinecraftBlock_Textures = require("./MinecraftBlock_Textures.bs.js");

function px(n) {
  return n.toString() + "px";
}

function deg(n) {
  return n.toString() + "deg";
}

function makeTileStyle(textureDef, frameIndex, size, width, height) {
  var y = Math.imul(Caml_int32.div(frameIndex, MinecraftBlock_Textures.textureSize), -size | 0);
  return Object.assign({}, {
              backgroundImage: "url(" + textureDef.url + ")",
              backgroundPosition: "0px " + (y.toString() + "px"),
              backgroundRepeat: "no-repeat",
              height: height.toString() + "px",
              width: width.toString() + "px",
              backgroundSize: "cover"
            }, {
              imageRendering: "pixelated"
            });
}

function makePreviewTileStyle(textureDef, textureFrame, rotation) {
  var width = 130;
  var height = 130;
  var base = {
    backgroundColor: "white",
    border: (1).toString() + "px" + " solid white",
    height: height.toString() + "px",
    width: width.toString() + "px",
    transform: "rotate(" + (Math.imul(rotation, 90).toString() + "deg") + ")"
  };
  if (textureFrame !== undefined) {
    return Object.assign({}, base, makeTileStyle(textureDef, textureFrame.frameIndex, 128, width, height));
  } else {
    return base;
  }
}

function makeGridTileStyle(textureDef, frameIndex) {
  var width = 40;
  return Object.assign({}, makeTileStyle(textureDef, frameIndex, 32, width, width), {
              borderWidth: (4).toString() + "px",
              display: "inline-block",
              marginRight: (6).toString() + "px",
              marginBottom: (6).toString() + "px"
            });
}

function makeGridTileClassName(isSelected) {
  if (isSelected) {
    return "border-blue-600";
  } else {
    return "border-gray-300 hover:border-gray-400";
  }
}

function MinecraftBlock_Components$TexturePicker$GridTile(Props) {
  var textureDef = Props.textureDef;
  var textureFrame = Props.textureFrame;
  var isSelected = Props.isSelected;
  var onClick = Props.onClick;
  var textureId = textureFrame.textureId;
  var className = makeGridTileClassName(isSelected);
  var style = makeGridTileStyle(textureDef, textureFrame.frameIndex);
  var title = MinecraftBlock_Textures.findTextureFrameCount(textureFrame.versionId, textureId) > 1 ? textureId + " (Frame " + textureFrame.frame.toString() + ")" : textureId;
  return React.createElement("button", {
              className: className,
              style: style,
              title: title,
              onClick: (function (param) {
                  return Curry._1(onClick, undefined);
                })
            }, React.createElement("span", {
                  dangerouslySetInnerHTML: {
                    __html: "&nbsp;"
                  }
                }));
}

var GridTile = {
  make: MinecraftBlock_Components$TexturePicker$GridTile
};

function MinecraftBlock_Components$TexturePicker$PreviewTile(Props) {
  var textureDef = Props.textureDef;
  var textureFrame = Props.textureFrame;
  var rotation = Props.rotation;
  var style = makePreviewTileStyle(textureDef, textureFrame, rotation);
  return React.createElement("div", {
              style: style
            });
}

var PreviewTile = {
  make: MinecraftBlock_Components$TexturePicker$PreviewTile
};

function MinecraftBlock_Components$TexturePicker(Props) {
  var versionId = Props.versionId;
  var onChange = Props.onChange;
  var match = React.useState(function () {
        
      });
  var setSelectedTextureFrame = match[1];
  var selectedTextureFrame = match[0];
  var match$1 = React.useState(function () {
        return 0;
      });
  var setRotation = match$1[1];
  var rotation = match$1[0];
  var textureFrames = MinecraftBlock_Textures.findTextureFrames(versionId);
  var textureDef = MinecraftBlock_Textures.findTextureDef(versionId);
  var textureIsSelected = function (textureId, frame) {
    if (selectedTextureFrame !== undefined && textureId === selectedTextureFrame.textureId) {
      return frame === selectedTextureFrame.frame;
    } else {
      return false;
    }
  };
  if (textureDef === undefined) {
    return null;
  }
  if (textureFrames === undefined) {
    return null;
  }
  var match$2 = React.useState(function () {
        
      });
  var setSearch = match$2[1];
  var search = match$2[0];
  var onSearchChange = function (e) {
    var target = e.target;
    var value = target.value;
    var value$1;
    if (value !== undefined) {
      var value$2 = Caml_option.valFromOption(value);
      value$1 = value$2.length === 0 ? undefined : Caml_option.some(value$2);
    } else {
      value$1 = undefined;
    }
    return Curry._1(setSearch, (function (param) {
                  return value$1;
                }));
  };
  var textures = search !== undefined ? textureFrames.filter(function (param) {
          return param.textureId.indexOf(search) >= 0;
        }) : textureFrames;
  var onRotate = function (param) {
    var rotation$1 = rotation + 1 | 0;
    var rotation$2 = rotation$1 > 3 ? 0 : rotation$1;
    Curry._1(setRotation, (function (param) {
            return rotation$2;
          }));
    if (selectedTextureFrame === undefined) {
      return ;
    }
    var faceTexture_versionId = selectedTextureFrame.versionId;
    var faceTexture_textureId = selectedTextureFrame.textureId;
    var faceTexture_frame = selectedTextureFrame.frame;
    var faceTexture = {
      versionId: faceTexture_versionId,
      textureId: faceTexture_textureId,
      frame: faceTexture_frame,
      rot: rotation$2
    };
    return Curry._1(onChange, MinecraftBlock_Face.encodeFaceTexture(faceTexture));
  };
  return React.createElement("div", {
              className: "mb-4"
            }, React.createElement("div", {
                  className: "font-bold"
                }, "Block Texture"), React.createElement("div", undefined, React.createElement("input", {
                      className: "p-2 mb-2 w-full",
                      placeholder: "Search",
                      onChange: onSearchChange
                    })), React.createElement("div", {
                  className: "flex w-full"
                }, React.createElement("div", {
                      className: "w-full"
                    }, React.createElement("div", {
                          className: "h-44 overflow-y-scroll"
                        }, textures.map(function (textureFrame) {
                              var frame = textureFrame.frame;
                              var textureId = textureFrame.textureId;
                              var key = textureId + ":" + frame.toString();
                              var onClick = function (param) {
                                Curry._1(setSelectedTextureFrame, (function (param) {
                                        return textureFrame;
                                      }));
                                Curry._1(setRotation, (function (param) {
                                        return 0;
                                      }));
                                var faceTexture = {
                                  versionId: versionId,
                                  textureId: textureId,
                                  frame: frame,
                                  rot: 0
                                };
                                return Curry._1(onChange, MinecraftBlock_Face.encodeFaceTexture(faceTexture));
                              };
                              return React.createElement(MinecraftBlock_Components$TexturePicker$GridTile, {
                                          textureDef: textureDef,
                                          textureFrame: textureFrame,
                                          isSelected: textureIsSelected(textureId, frame),
                                          onClick: onClick,
                                          key: key
                                        });
                            }))), React.createElement("div", {
                      className: "flex flex-col w-40 items-center px-8"
                    }, React.createElement(MinecraftBlock_Components$TexturePicker$PreviewTile, {
                          textureDef: textureDef,
                          textureFrame: selectedTextureFrame,
                          rotation: rotation
                        }), React.createElement("div", undefined, React.createElement("button", {
                              className: "bg-blue-500 rounded text-white my-4 py-1 px-4 text-center",
                              onClick: onRotate
                            }, "Rotate")))));
}

var TexturePicker = {
  px: px,
  deg: deg,
  makeTileStyle: makeTileStyle,
  makePreviewTileStyle: makePreviewTileStyle,
  makeGridTileStyle: makeGridTileStyle,
  makeGridTileClassName: makeGridTileClassName,
  GridTile: GridTile,
  PreviewTile: PreviewTile,
  make: MinecraftBlock_Components$TexturePicker
};

var Textures;

var Face;

exports.Textures = Textures;
exports.Face = Face;
exports.TexturePicker = TexturePicker;
/* react Not a pure module */
