// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("./demo/Demo.bs.js");
var Example = require("./example/Example.bs.js");

var generators = [
  Example.generator,
  Demo.generator
];

exports.generators = generators;
/* Demo Not a pure module */
