// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Generator = require("../../builder/modules/Generator.bs.js");
var TextureMap = require("../TextureMap.bs.js");

function requireImage(id) {
  return require("./images/" + id + ".png");
}

function requireTexture(id) {
  return require("./textures/" + id + ".png");
}

var id = "minecraft-character-mini";

var name = "Minecraft Character Mini";

var thumbnail = {
  url: require("./thumbnail/v2-thumbnail-256.jpeg")
};

var images = [
  {
    id: "Skin Overlay",
    url: requireImage("skin-overlay")
  },
  {
    id: "Skin Background",
    url: requireImage("skin-background")
  }
];

var textures = [{
    id: "Skin",
    url: requireTexture("Steve"),
    standardWidth: 64,
    standardHeight: 64
  }];

var steve = TextureMap.MinecraftCharacterLegacy.steve;

var alex = TextureMap.MinecraftCharacterLegacy.alex;

function drawMini(options) {
  var skin = options.skin;
  var x = options.x;
  var y = options.y;
  var alexModel = options.alexModel;
  var showHeadOverlay = options.showHeadOverlay;
  var showBodyOverlay = options.showBodyOverlay;
  var showArmOverlay = options.showArmOverlay;
  var showLegOverlay = options.showLegOverlay;
  var bodyHeight = options.bodyHeight;
  var legHeight = 64 - bodyHeight | 0;
  Generator.drawImage("Skin Background", [
        x,
        y
      ]);
  var ox = x + 49 | 0;
  var oy = y + 90 | 0;
  Generator.drawTextureLegacy(skin, steve.base.head.right, {
        x: ox,
        y: oy,
        w: 64,
        h: 64
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.head.front, {
        x: ox + 64 | 0,
        y: oy,
        w: 64,
        h: 64
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.head.left, {
        x: ox + 128 | 0,
        y: oy,
        w: 64,
        h: 64
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.head.back, {
        x: ox + 192 | 0,
        y: oy,
        w: 64,
        h: 64
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.head.top, {
        x: ox + 64 | 0,
        y: oy - 64 | 0,
        w: 64,
        h: 64
      }, undefined, undefined, undefined);
  if (showHeadOverlay) {
    Generator.drawTextureLegacy(skin, steve.overlay.head.right, {
          x: ox,
          y: oy,
          w: 64,
          h: 64
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.head.front, {
          x: ox + 64 | 0,
          y: oy,
          w: 64,
          h: 64
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.head.left, {
          x: ox + 128 | 0,
          y: oy,
          w: 64,
          h: 64
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.head.back, {
          x: ox + 192 | 0,
          y: oy,
          w: 64,
          h: 64
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.head.top, {
          x: ox + 64 | 0,
          y: oy - 64 | 0,
          w: 64,
          h: 64
        }, undefined, undefined, undefined);
  }
  var ox$1 = x + 49 | 0;
  var oy$1 = y + 26 | 0;
  Generator.drawTextureLegacy(skin, steve.base.head.right, {
        x: ox$1 + 64 | 0,
        y: oy$1,
        w: 64,
        h: 64
      }, undefined, 90.0, undefined);
  Generator.drawTextureLegacy(skin, steve.base.head.left, {
        x: ox$1 + 128 | 0,
        y: oy$1 + 64 | 0,
        w: 64,
        h: 64
      }, undefined, -90.0, undefined);
  if (showHeadOverlay) {
    Generator.drawTextureLegacy(skin, steve.overlay.head.right, {
          x: ox$1 + 64 | 0,
          y: oy$1,
          w: 64,
          h: 64
        }, undefined, 90.0, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.head.left, {
          x: ox$1 + 128 | 0,
          y: oy$1 + 64 | 0,
          w: 64,
          h: 64
        }, undefined, -90.0, undefined);
  }
  var ox$2 = x + 49 | 0;
  var oy$2 = y + 154 | 0;
  Generator.drawTextureLegacy(skin, steve.base.body.right, {
        x: ox$2,
        y: oy$2,
        w: 64,
        h: bodyHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.body.front, {
        x: ox$2 + 64 | 0,
        y: oy$2,
        w: 64,
        h: bodyHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.body.left, {
        x: ox$2 + 128 | 0,
        y: oy$2,
        w: 64,
        h: bodyHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.body.back, {
        x: ox$2 + 192 | 0,
        y: oy$2,
        w: 64,
        h: bodyHeight
      }, undefined, undefined, undefined);
  if (showBodyOverlay) {
    Generator.drawTextureLegacy(skin, steve.overlay.body.right, {
          x: ox$2,
          y: oy$2,
          w: 64,
          h: bodyHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.body.front, {
          x: ox$2 + 64 | 0,
          y: oy$2,
          w: 64,
          h: bodyHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.body.left, {
          x: ox$2 + 128 | 0,
          y: oy$2,
          w: 64,
          h: bodyHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.body.back, {
          x: ox$2 + 192 | 0,
          y: oy$2,
          w: 64,
          h: bodyHeight
        }, undefined, undefined, undefined);
  }
  if (alexModel) {
    var ox$3 = x + 49 | 0;
    var oy$3 = y + 10 | 0;
    Generator.drawTextureLegacy(skin, alex.base.rightArm.left, {
          x: ox$3,
          y: oy$3,
          w: 32,
          h: 48
        }, undefined, 90.0, undefined);
    Generator.drawTextureLegacy(skin, alex.base.rightArm.right, {
          x: ox$3,
          y: oy$3 + 32 | 0,
          w: 32,
          h: 48
        }, undefined, 90.0, undefined);
    if (showArmOverlay) {
      Generator.drawTextureLegacy(skin, alex.overlay.rightArm.left, {
            x: ox$3,
            y: oy$3,
            w: 32,
            h: 48
          }, undefined, 90.0, undefined);
      Generator.drawTextureLegacy(skin, alex.overlay.rightArm.right, {
            x: ox$3,
            y: oy$3 + 32 | 0,
            w: 32,
            h: 48
          }, undefined, 90.0, undefined);
    }
    var ox$4 = x + 241 | 0;
    var oy$4 = y + 42 | 0;
    Generator.drawTextureLegacy(skin, alex.base.leftArm.right, {
          x: ox$4,
          y: oy$4,
          w: 32,
          h: 48
        }, undefined, -90.0, undefined);
    Generator.drawTextureLegacy(skin, alex.base.leftArm.left, {
          x: ox$4,
          y: oy$4 + 32 | 0,
          w: 32,
          h: 48
        }, undefined, -90.0, undefined);
    if (showArmOverlay) {
      Generator.drawTextureLegacy(skin, alex.overlay.leftArm.right, {
            x: ox$4,
            y: oy$4,
            w: 32,
            h: 48
          }, undefined, -90.0, undefined);
      Generator.drawTextureLegacy(skin, alex.overlay.leftArm.left, {
            x: ox$4,
            y: oy$4 + 32 | 0,
            w: 32,
            h: 48
          }, undefined, -90.0, undefined);
    }
    
  } else {
    var ox$5 = x + 49 | 0;
    var oy$5 = y + 10 | 0;
    Generator.drawTextureLegacy(skin, steve.base.rightArm.left, {
          x: ox$5,
          y: oy$5,
          w: 32,
          h: 48
        }, undefined, 90.0, undefined);
    Generator.drawTextureLegacy(skin, steve.base.rightArm.right, {
          x: ox$5,
          y: oy$5 + 32 | 0,
          w: 32,
          h: 48
        }, undefined, 90.0, undefined);
    if (showArmOverlay) {
      Generator.drawTextureLegacy(skin, steve.overlay.rightArm.left, {
            x: ox$5,
            y: oy$5,
            w: 32,
            h: 48
          }, undefined, 90.0, undefined);
      Generator.drawTextureLegacy(skin, steve.overlay.rightArm.right, {
            x: ox$5,
            y: oy$5 + 32 | 0,
            w: 32,
            h: 48
          }, undefined, 90.0, undefined);
    }
    var ox$6 = x + 241 | 0;
    var oy$6 = y + 42 | 0;
    Generator.drawTextureLegacy(skin, steve.base.leftArm.right, {
          x: ox$6,
          y: oy$6,
          w: 32,
          h: 48
        }, undefined, -90.0, undefined);
    Generator.drawTextureLegacy(skin, steve.base.leftArm.left, {
          x: ox$6,
          y: oy$6 + 32 | 0,
          w: 32,
          h: 48
        }, undefined, -90.0, undefined);
    if (showArmOverlay) {
      Generator.drawTextureLegacy(skin, steve.overlay.leftArm.right, {
            x: ox$6,
            y: oy$6,
            w: 32,
            h: 48
          }, undefined, -90.0, undefined);
      Generator.drawTextureLegacy(skin, steve.overlay.leftArm.left, {
            x: ox$6,
            y: oy$6 + 32 | 0,
            w: 32,
            h: 48
          }, undefined, -90.0, undefined);
    }
    
  }
  var ox$7 = x + 49 | 0;
  var oy$7 = y + 154 | 0;
  Generator.drawTextureLegacy(skin, steve.base.rightLeg.front, {
        x: ox$7 + 64 | 0,
        y: oy$7 + bodyHeight | 0,
        w: 32,
        h: legHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.rightLeg.right, {
        x: ox$7,
        y: oy$7 + bodyHeight | 0,
        w: 64,
        h: legHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.rightLeg.back, {
        x: ox$7 + 224 | 0,
        y: oy$7 + bodyHeight | 0,
        w: 32,
        h: legHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.rightLeg.bottom, {
        x: ox$7 + 64 | 0,
        y: oy$7 + 64 | 0,
        w: 32,
        h: 64
      }, "Vertical", undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.leftLeg.front, {
        x: ox$7 + 96 | 0,
        y: oy$7 + bodyHeight | 0,
        w: 32,
        h: legHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.leftLeg.left, {
        x: ox$7 + 128 | 0,
        y: oy$7 + bodyHeight | 0,
        w: 64,
        h: legHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.leftLeg.back, {
        x: ox$7 + 192 | 0,
        y: oy$7 + bodyHeight | 0,
        w: 32,
        h: legHeight
      }, undefined, undefined, undefined);
  Generator.drawTextureLegacy(skin, steve.base.leftLeg.bottom, {
        x: ox$7 + 96 | 0,
        y: oy$7 + 64 | 0,
        w: 32,
        h: 64
      }, "Vertical", undefined, undefined);
  if (showLegOverlay) {
    Generator.drawTextureLegacy(skin, steve.overlay.rightLeg.front, {
          x: ox$7 + 64 | 0,
          y: oy$7 + bodyHeight | 0,
          w: 32,
          h: legHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.rightLeg.right, {
          x: ox$7,
          y: oy$7 + bodyHeight | 0,
          w: 64,
          h: legHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.rightLeg.back, {
          x: ox$7 + 224 | 0,
          y: oy$7 + bodyHeight | 0,
          w: 32,
          h: legHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.rightLeg.bottom, {
          x: ox$7 + 64 | 0,
          y: oy$7 + 64 | 0,
          w: 32,
          h: 64
        }, "Vertical", undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.leftLeg.front, {
          x: ox$7 + 96 | 0,
          y: oy$7 + bodyHeight | 0,
          w: 32,
          h: legHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.leftLeg.left, {
          x: ox$7 + 128 | 0,
          y: oy$7 + bodyHeight | 0,
          w: 64,
          h: legHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.leftLeg.back, {
          x: ox$7 + 192 | 0,
          y: oy$7 + bodyHeight | 0,
          w: 32,
          h: legHeight
        }, undefined, undefined, undefined);
    Generator.drawTextureLegacy(skin, steve.overlay.leftLeg.bottom, {
          x: ox$7 + 96 | 0,
          y: oy$7 + 64 | 0,
          w: 32,
          h: 64
        }, "Vertical", undefined, undefined);
  }
  return Generator.drawImage("Skin Overlay", [
              x,
              y
            ]);
}

function script(param) {
  Generator.defineTextureInput("Skin 1", {
        standardWidth: 64,
        standardHeight: 64,
        choices: []
      });
  Generator.defineTextureInput("Skin 2", {
        standardWidth: 64,
        standardHeight: 64,
        choices: []
      });
  var showSkin1 = Generator.hasTexture("Skin 1");
  var showSkin2 = Generator.hasTexture("Skin 2");
  if (showSkin1) {
    Generator.defineSelectInput("Skin 1 Model Type", [
          "Steve",
          "Alex"
        ]);
    var modelType1 = Generator.getSelectInputValue("Skin 1 Model Type");
    Generator.defineBooleanInput("Skin 1 Head Overlay", true);
    Generator.defineBooleanInput("Skin 1 Body Overlay", true);
    Generator.defineBooleanInput("Skin 1 Arm Overlay", true);
    Generator.defineBooleanInput("Skin 1 Leg Overlay", true);
    Generator.defineRangeInput("Skin 1 Body Height", {
          min: 0,
          max: 64,
          value: 32,
          step: 1
        });
    var alexModel1 = modelType1 === "Alex";
    var showSkin1HeadOverlay = Generator.getBooleanInputValue("Skin 1 Head Overlay");
    var showSkin1BodyOverlay = Generator.getBooleanInputValue("Skin 1 Body Overlay");
    var showSkin1ArmOverlay = Generator.getBooleanInputValue("Skin 1 Arm Overlay");
    var showSkin1LegOverlay = Generator.getBooleanInputValue("Skin 1 Leg Overlay");
    var skin1BodyHeight = Generator.getRangeInputValue("Skin 1 Body Height");
    drawMini({
          skin: "Skin 1",
          x: 151,
          y: 108,
          alexModel: alexModel1,
          showHeadOverlay: showSkin1HeadOverlay,
          showBodyOverlay: showSkin1BodyOverlay,
          showArmOverlay: showSkin1ArmOverlay,
          showLegOverlay: showSkin1LegOverlay,
          bodyHeight: skin1BodyHeight
        });
  }
  if (!showSkin2) {
    return ;
  }
  Generator.defineSelectInput("Skin 2 Model Type", [
        "Steve",
        "Alex"
      ]);
  var modelType2 = Generator.getSelectInputValue("Skin 2 Model Type");
  Generator.defineBooleanInput("Skin 2 Head Overlay", true);
  Generator.defineBooleanInput("Skin 2 Body Overlay", true);
  Generator.defineBooleanInput("Skin 2 Arm Overlay", true);
  Generator.defineBooleanInput("Skin 2 Leg Overlay", true);
  Generator.defineRangeInput("Skin 2 Body Height", {
        min: 0,
        max: 64,
        value: 32,
        step: 1
      });
  var alexModel2 = modelType2 === "Alex";
  var showSkin2HeadOverlay = Generator.getBooleanInputValue("Skin 2 Head Overlay");
  var showSkin2BodyOverlay = Generator.getBooleanInputValue("Skin 2 Body Overlay");
  var showSkin2ArmOverlay = Generator.getBooleanInputValue("Skin 2 Arm Overlay");
  var showSkin2LegOverlay = Generator.getBooleanInputValue("Skin 2 Leg Overlay");
  var skin2BodyHeight = Generator.getRangeInputValue("Skin 2 Body Height");
  return drawMini({
              skin: "Skin 2",
              x: 151,
              y: 453,
              alexModel: alexModel2,
              showHeadOverlay: showSkin2HeadOverlay,
              showBodyOverlay: showSkin2BodyOverlay,
              showArmOverlay: showSkin2ArmOverlay,
              showLegOverlay: showSkin2LegOverlay,
              bodyHeight: skin2BodyHeight
            });
}

var generator_thumbnail = thumbnail;

var generator = {
  id: id,
  name: name,
  thumbnail: generator_thumbnail,
  video: undefined,
  instructions: undefined,
  images: images,
  textures: textures,
  script: script
};

exports.requireImage = requireImage;
exports.requireTexture = requireTexture;
exports.id = id;
exports.name = name;
exports.thumbnail = thumbnail;
exports.images = images;
exports.textures = textures;
exports.steve = steve;
exports.alex = alex;
exports.drawMini = drawMini;
exports.script = script;
exports.generator = generator;
/* thumbnail Not a pure module */
