// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Builder = require("./Builder.bs.js");
var Generator = require("./Generator.bs.js");

function run(generatorDef, model) {
  return new Promise((function (resolve, _reject) {
                setTimeout((function (param) {
                        var init = Builder.Model.make(undefined);
                        var model_inputs = init.inputs;
                        var model_pages = init.pages;
                        var model_currentPage = init.currentPage;
                        var model_values = model.values;
                        var model$1 = {
                          inputs: model_inputs,
                          pages: model_pages,
                          currentPage: model_currentPage,
                          values: model_values
                        };
                        Generator.setModel(model$1);
                        Curry._1(generatorDef.script, undefined);
                        return resolve(Generator.getModel(undefined));
                      }), 1);
                
              }));
}

exports.run = run;
/* Generator Not a pure module */
