// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Generator = require("../../builder/modules/Generator.bs.js");

function requireImage(fileName) {
  return require("./images/" + fileName);
}

function requireTexture(fileName) {
  return require("./textures/" + fileName);
}

var id = "minecraft-allay-character";

var name = "Minecraft Allay Character";

var images = [{
    id: "Overlay",
    url: require("./images/OverlayAllay.png")
  }];

var textures = [
  {
    id: "Skin1",
    url: require("./textures/Skin1.png"),
    standardWidth: 64,
    standardHeight: 64
  },
  {
    id: "Skin2",
    url: require("./textures/Skin2.png"),
    standardWidth: 64,
    standardHeight: 64
  }
];

var allay_head = {
  top: [
    8,
    0,
    8,
    8
  ],
  bottom: [
    16,
    0,
    8,
    8
  ],
  front: [
    8,
    8,
    8,
    8
  ],
  right: [
    0,
    8,
    8,
    8
  ],
  left: [
    16,
    8,
    8,
    8
  ],
  back: [
    24,
    8,
    8,
    8
  ],
  topOverlay: [
    40,
    0,
    8,
    8
  ],
  bottomOverlay: [
    48,
    0,
    8,
    8
  ],
  frontOverlay: [
    40,
    8,
    8,
    8
  ],
  rightOverlay: [
    32,
    8,
    8,
    8
  ],
  leftOverlay: [
    48,
    8,
    8,
    8
  ],
  backOverlay: [
    56,
    8,
    8,
    8
  ]
};

var allay_body = {
  top: [
    20,
    16,
    8,
    4
  ],
  bottom: [
    28,
    16,
    8,
    4
  ],
  front: [
    20,
    20,
    8,
    12
  ],
  right: [
    16,
    20,
    4,
    12
  ],
  left: [
    28,
    20,
    4,
    12
  ],
  back: [
    32,
    20,
    8,
    12
  ],
  topOverlay: [
    20,
    32,
    8,
    4
  ],
  bottomOverlay: [
    28,
    32,
    8,
    4
  ],
  frontOverlay: [
    20,
    36,
    8,
    12
  ],
  rightOverlay: [
    16,
    36,
    4,
    12
  ],
  leftOverlay: [
    28,
    36,
    4,
    12
  ],
  backOverlay: [
    32,
    36,
    8,
    12
  ]
};

var allay_rightLeg = {
  top: [
    4,
    16,
    4,
    4
  ],
  bottom: [
    8,
    16,
    4,
    4
  ],
  front: [
    4,
    20,
    4,
    12
  ],
  right: [
    0,
    20,
    4,
    12
  ],
  left: [
    8,
    20,
    4,
    12
  ],
  back: [
    12,
    20,
    4,
    12
  ],
  topOverlay: [
    4,
    32,
    4,
    4
  ],
  bottomOverlay: [
    8,
    32,
    4,
    4
  ],
  frontOverlay: [
    4,
    36,
    4,
    12
  ],
  rightOverlay: [
    0,
    36,
    4,
    12
  ],
  leftOverlay: [
    8,
    36,
    4,
    12
  ],
  backOverlay: [
    12,
    36,
    4,
    12
  ]
};

var allay_leftLeg = {
  top: [
    20,
    48,
    4,
    4
  ],
  bottom: [
    24,
    48,
    4,
    4
  ],
  front: [
    20,
    52,
    4,
    12
  ],
  right: [
    16,
    52,
    4,
    12
  ],
  left: [
    24,
    52,
    4,
    12
  ],
  back: [
    28,
    52,
    4,
    12
  ],
  topOverlay: [
    4,
    48,
    4,
    4
  ],
  bottomOverlay: [
    8,
    48,
    4,
    4
  ],
  frontOverlay: [
    4,
    52,
    4,
    12
  ],
  rightOverlay: [
    0,
    52,
    4,
    12
  ],
  leftOverlay: [
    8,
    52,
    4,
    12
  ],
  backOverlay: [
    12,
    52,
    4,
    12
  ]
};

var allay_rightArm = {
  top: [
    44,
    16,
    4,
    4
  ],
  bottom: [
    48,
    16,
    4,
    4
  ],
  front: [
    44,
    20,
    4,
    12
  ],
  right: [
    40,
    20,
    4,
    12
  ],
  left: [
    48,
    20,
    4,
    12
  ],
  back: [
    52,
    20,
    4,
    12
  ],
  topOverlay: [
    44,
    32,
    4,
    4
  ],
  bottomOverlay: [
    48,
    32,
    4,
    4
  ],
  frontOverlay: [
    44,
    36,
    4,
    12
  ],
  rightOverlay: [
    40,
    36,
    4,
    12
  ],
  leftOverlay: [
    48,
    36,
    4,
    12
  ],
  backOverlay: [
    52,
    36,
    4,
    12
  ]
};

var allay_leftArm = {
  top: [
    44,
    16,
    4,
    4
  ],
  bottom: [
    48,
    16,
    4,
    4
  ],
  front: [
    44,
    20,
    4,
    12
  ],
  right: [
    40,
    20,
    4,
    12
  ],
  left: [
    48,
    20,
    4,
    12
  ],
  back: [
    52,
    20,
    4,
    12
  ],
  topOverlay: [
    60,
    16,
    4,
    4
  ],
  bottomOverlay: [
    64,
    16,
    4,
    4
  ],
  frontOverlay: [
    60,
    20,
    4,
    12
  ],
  rightOverlay: [
    56,
    20,
    4,
    12
  ],
  leftOverlay: [
    64,
    20,
    4,
    12
  ],
  backOverlay: [
    68,
    20,
    4,
    12
  ]
};

var allay_rightArmAlex = {
  top: [
    44,
    16,
    3,
    4
  ],
  bottom: [
    47,
    16,
    3,
    4
  ],
  front: [
    44,
    20,
    3,
    12
  ],
  right: [
    40,
    20,
    4,
    12
  ],
  left: [
    47,
    20,
    4,
    12
  ],
  back: [
    51,
    20,
    3,
    12
  ],
  topOverlay: [
    44,
    32,
    3,
    4
  ],
  bottomOverlay: [
    47,
    32,
    3,
    4
  ],
  frontOverlay: [
    44,
    36,
    3,
    12
  ],
  rightOverlay: [
    40,
    36,
    4,
    12
  ],
  leftOverlay: [
    47,
    36,
    4,
    12
  ],
  backOverlay: [
    51,
    36,
    3,
    12
  ]
};

var allay_leftArmAlex = {
  top: [
    44,
    16,
    3,
    4
  ],
  bottom: [
    47,
    16,
    3,
    4
  ],
  front: [
    44,
    20,
    3,
    12
  ],
  right: [
    40,
    20,
    4,
    12
  ],
  left: [
    47,
    20,
    4,
    12
  ],
  back: [
    51,
    20,
    3,
    12
  ],
  topOverlay: [
    58,
    16,
    3,
    4
  ],
  bottomOverlay: [
    61,
    16,
    3,
    4
  ],
  frontOverlay: [
    58,
    20,
    3,
    12
  ],
  rightOverlay: [
    54,
    20,
    4,
    12
  ],
  leftOverlay: [
    61,
    20,
    4,
    12
  ],
  backOverlay: [
    65,
    20,
    3,
    12
  ]
};

var allay = {
  head: allay_head,
  body: allay_body,
  rightLeg: allay_rightLeg,
  leftLeg: allay_leftLeg,
  rightArm: allay_rightArm,
  leftArm: allay_leftArm,
  rightArmAlex: allay_rightArmAlex,
  leftArmAlex: allay_leftArmAlex
};

var TextureMap = {
  allay: allay
};

function drawHead1(ox, oy) {
  Generator.drawTexture("Skin1", allay_head.front, [
        ox,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.right, [
        ox - 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.left, [
        ox + 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.back, [
        ox + 102 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.top, [
        ox,
        oy - 51 | 0,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.bottom, [
        ox,
        oy + 51 | 0,
        50,
        50
      ], "Vertical", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.frontOverlay, [
        ox,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.rightOverlay, [
        ox - 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.leftOverlay, [
        ox + 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.backOverlay, [
        ox + 102 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_head.topOverlay, [
        ox,
        oy - 51 | 0,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin1", allay_head.bottomOverlay, [
              ox,
              oy + 51 | 0,
              50,
              50
            ], "Vertical", undefined, undefined, undefined, undefined, undefined);
}

function drawBody1(ox, oy) {
  Generator.drawTexture("Skin1", allay_body.front, [
        ox,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.right, [
        ox - 21 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.left, [
        ox + 31 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.back, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.top, [
        ox,
        oy - 21 | 0,
        30,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.front, [
        ((ox - 21 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.right, [
        (ox - 21 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.left, [
        (((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.back, [
        ((((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.top, [
        ((ox - 21 | 0) - 21 | 0) - 31 | 0,
        oy - 21 | 0,
        30,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.frontOverlay, [
        ox,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.leftOverlay, [
        ox + 31 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.backOverlay, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.topOverlay, [
        ox,
        oy - 21 | 0,
        30,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.frontOverlay, [
        ((ox - 21 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.rightOverlay, [
        (ox - 21 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.leftOverlay, [
        (((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.backOverlay, [
        ((((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin1", allay_body.topOverlay, [
              ((ox - 21 | 0) - 21 | 0) - 31 | 0,
              oy - 21 | 0,
              30,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawRightArm1(ox, oy) {
  Generator.drawTexture("Skin1", allay_rightArm.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.back, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.backOverlay, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArm.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin1", allay_rightArm.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawLeftArm1(ox, oy) {
  Generator.drawTexture("Skin1", allay_leftArm.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.back, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.backOverlay, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArm.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin1", allay_leftArm.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawRightArm1Alex(ox, oy) {
  Generator.drawTexture("Skin1", allay_rightArmAlex.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.back, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.backOverlay, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightArmAlex.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin1", allay_rightArmAlex.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawLeftArm1Alex(ox, oy) {
  Generator.drawTexture("Skin1", allay_leftArmAlex.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.back, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.backOverlay, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftArmAlex.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin1", allay_leftArmAlex.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawLegs1(ox, oy) {
  Generator.drawTexture("Skin1", allay_body.front, [
        ox,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.right, [
        ox - 21 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.left, [
        ox + 31 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.back, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.front, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.right, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.left, [
        (((ox + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.back, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.front, [
        ox,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.right, [
        ox - 21 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.back, [
        ((ox + 31 | 0) + 21 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.front, [
        ox + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.left, [
        ox + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.back, [
        (ox + 31 | 0) + 21 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.front, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.right, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.back, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.front, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.left, [
        (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.back, [
        (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.frontOverlay, [
        ox,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.leftOverlay, [
        ox + 31 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.backOverlay, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.frontOverlay, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.rightOverlay, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.leftOverlay, [
        (((ox + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.backOverlay, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.frontOverlay, [
        ox,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.rightOverlay, [
        ox - 21 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.backOverlay, [
        ((ox + 31 | 0) + 21 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.frontOverlay, [
        ox + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.leftOverlay, [
        ox + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.backOverlay, [
        (ox + 31 | 0) + 21 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.frontOverlay, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.rightOverlay, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_rightLeg.backOverlay, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.frontOverlay, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_leftLeg.leftOverlay, [
        (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin1", allay_leftLeg.backOverlay, [
              (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
              oy + 25 | 0,
              15,
              25
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawHead2(ox, oy) {
  Generator.drawTexture("Skin2", allay_head.front, [
        ox,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.right, [
        ox - 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.left, [
        ox + 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.back, [
        ox + 102 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.top, [
        ox,
        oy - 51 | 0,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.bottom, [
        ox,
        oy + 51 | 0,
        50,
        50
      ], "Vertical", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.frontOverlay, [
        ox,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.rightOverlay, [
        ox - 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.leftOverlay, [
        ox + 51 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.backOverlay, [
        ox + 102 | 0,
        oy,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_head.topOverlay, [
        ox,
        oy - 51 | 0,
        50,
        50
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin2", allay_head.bottomOverlay, [
              ox,
              oy + 51 | 0,
              50,
              50
            ], "Vertical", undefined, undefined, undefined, undefined, undefined);
}

function drawBody2(ox, oy) {
  Generator.drawTexture("Skin2", allay_body.front, [
        ox,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.right, [
        ox - 21 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.left, [
        ox + 31 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.back, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.top, [
        ox,
        oy - 21 | 0,
        30,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.front, [
        ((ox - 21 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.right, [
        (ox - 21 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.left, [
        (((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.back, [
        ((((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.top, [
        ((ox - 21 | 0) - 21 | 0) - 31 | 0,
        oy - 21 | 0,
        30,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.frontOverlay, [
        ox,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.leftOverlay, [
        ox + 31 | 0,
        oy,
        20,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.backOverlay, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        30
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin1", allay_body.topOverlay, [
        ox,
        oy - 21 | 0,
        30,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.frontOverlay, [
        ((ox - 21 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.rightOverlay, [
        (ox - 21 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.leftOverlay, [
        (((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0,
        oy,
        20,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.backOverlay, [
        ((((ox - 21 | 0) - 21 | 0) - 31 | 0) - 21 | 0) - 31 | 0,
        oy,
        30,
        30
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin2", allay_body.topOverlay, [
              ((ox - 21 | 0) - 21 | 0) - 31 | 0,
              oy - 21 | 0,
              30,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawRightArm2(ox, oy) {
  Generator.drawTexture("Skin2", allay_rightArm.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.back, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.backOverlay, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArm.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin2", allay_rightArm.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawLeftArm2(ox, oy) {
  Generator.drawTexture("Skin2", allay_leftArm.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.back, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.backOverlay, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArm.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin2", allay_leftArm.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawRightArm2Alex(ox, oy) {
  Generator.drawTexture("Skin2", allay_rightArmAlex.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.back, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.backOverlay, [
        (ox - 11 | 0) - 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightArmAlex.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin2", allay_rightArmAlex.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawLeftArm2Alex(ox, oy) {
  Generator.drawTexture("Skin2", allay_leftArmAlex.front, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.right, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.left, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.back, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.top, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.bottom, [
        ox,
        oy + 41 | 0,
        10,
        20
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.frontOverlay, [
        ox,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.leftOverlay, [
        ox + 11 | 0,
        oy,
        20,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.backOverlay, [
        (ox + 11 | 0) + 21 | 0,
        oy,
        10,
        40
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftArmAlex.topOverlay, [
        ox,
        oy - 21 | 0,
        10,
        20
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin2", allay_leftArmAlex.bottomOverlay, [
              ox,
              oy + 41 | 0,
              10,
              20
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

function drawLegs2(ox, oy) {
  Generator.drawTexture("Skin2", allay_body.front, [
        ox,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.right, [
        ox - 21 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.left, [
        ox + 31 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.back, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.front, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.right, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.left, [
        (((ox + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.back, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.front, [
        ox,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.right, [
        ox - 21 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.back, [
        ((ox + 31 | 0) + 21 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.front, [
        ox + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.left, [
        ox + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.back, [
        (ox + 31 | 0) + 21 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.front, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.right, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.back, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.front, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.left, [
        (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.back, [
        (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.frontOverlay, [
        ox,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.rightOverlay, [
        ox - 21 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.leftOverlay, [
        ox + 31 | 0,
        oy,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.backOverlay, [
        (ox + 31 | 0) + 21 | 0,
        oy,
        30,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.frontOverlay, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.rightOverlay, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.leftOverlay, [
        (((ox + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_body.backOverlay, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy,
        30,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.frontOverlay, [
        ox,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.rightOverlay, [
        ox - 21 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.backOverlay, [
        ((ox + 31 | 0) + 21 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.frontOverlay, [
        ox + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.leftOverlay, [
        ox + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.backOverlay, [
        (ox + 31 | 0) + 21 | 0,
        oy + 25 | 0,
        15,
        25
      ], undefined, undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.frontOverlay, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.rightOverlay, [
        (((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_rightLeg.backOverlay, [
        ((ox + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.frontOverlay, [
        ((((ox + 31 | 0) + 21 | 0) + 31 | 0) + 21 | 0) + 31 | 0,
        oy + 25 | 0,
        15,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  Generator.drawTexture("Skin2", allay_leftLeg.leftOverlay, [
        (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 31 | 0,
        oy + 25 | 0,
        20,
        25
      ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
  return Generator.drawTexture("Skin2", allay_leftLeg.backOverlay, [
              (((ox + 31 | 0) + 21 | 0) + 31 | 0) + 15 | 0,
              oy + 25 | 0,
              15,
              25
            ], "Horizontal", undefined, undefined, undefined, undefined, undefined);
}

var Drawing = {
  drawHead1: drawHead1,
  drawBody1: drawBody1,
  drawRightArm1: drawRightArm1,
  drawLeftArm1: drawLeftArm1,
  drawRightArm1Alex: drawRightArm1Alex,
  drawLeftArm1Alex: drawLeftArm1Alex,
  drawLegs1: drawLegs1,
  drawHead2: drawHead2,
  drawBody2: drawBody2,
  drawRightArm2: drawRightArm2,
  drawLeftArm2: drawLeftArm2,
  drawRightArm2Alex: drawRightArm2Alex,
  drawLeftArm2Alex: drawLeftArm2Alex,
  drawLegs2: drawLegs2
};

function script(param) {
  Generator.defineSelectInput("Character 1 skin model type", [
        "Steve",
        "Alex"
      ]);
  Generator.defineTextureInput("Skin1", {
        standardWidth: 64,
        standardHeight: 64,
        choices: []
      });
  var alexModel1 = Generator.getSelectInputValue("Character 1 skin model type") === "Alex";
  Generator.defineSelectInput("Character 2 skin model type", [
        "Steve",
        "Alex"
      ]);
  Generator.defineTextureInput("Skin2", {
        standardWidth: 64,
        standardHeight: 64,
        choices: []
      });
  var alexModel2 = Generator.getSelectInputValue("Character 2 skin model type") === "Alex";
  drawHead1(62, 63);
  drawBody1(422, 84);
  if (alexModel1) {
    drawRightArm1Alex(186, 198);
    drawLeftArm1Alex(48, 198);
  } else {
    drawRightArm1(186, 198);
    drawLeftArm1(48, 198);
  }
  drawLegs1(279, 197);
  drawHead2(62, 424);
  drawBody2(422, 445);
  if (alexModel2) {
    drawRightArm2Alex(186, 559);
    drawLeftArm2Alex(48, 559);
  } else {
    drawRightArm2(186, 559);
    drawLeftArm2(48, 559);
  }
  drawLegs2(278, 559);
  return Generator.drawImage("Overlay", [
              0,
              0
            ]);
}

var generator = {
  id: id,
  name: name,
  thumbnail: undefined,
  video: undefined,
  instructions: undefined,
  images: images,
  textures: textures,
  script: script
};

exports.requireImage = requireImage;
exports.requireTexture = requireTexture;
exports.id = id;
exports.name = name;
exports.images = images;
exports.textures = textures;
exports.TextureMap = TextureMap;
exports.Drawing = Drawing;
exports.script = script;
exports.generator = generator;
/* images Not a pure module */
