// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Generator = require("../../builder/modules/Generator.bs.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

function requireImage(fileName) {
  return require("./images/" + fileName);
}

function requireTexture(fileName) {
  return require("./textures/" + fileName);
}

var id = "biome";

var name = "Biome";

var images = [
  {
    id: "Background",
    url: require("./images/Background.png")
  },
  {
    id: "Folds",
    url: require("./images/Folds.png")
  }
];

var textures = [{
    id: "Skin",
    url: require("./textures/Skin.png"),
    standardWidth: 64,
    standardHeight: 64
  }];

function script(param) {
  Generator.defineSelectInput("Diorama Size", [
        "2x2",
        "5x5",
        "8x8"
      ]);
  Generator.defineSelectInput("Biome", [
        "Plains",
        "Desert",
        "Gravel Mountain",
        "Badlands",
        "Snow Plains",
        "Nether Wastes",
        "Soulsand walley",
        "Crimson Forest",
        "Warped Forest",
        "End",
        "Basalt Deltas"
      ]);
  Generator.getSelectInputValue("Diorama Size") === "2x2";
  Generator.getSelectInputValue("Diorama Size") === "5x5";
  Generator.getSelectInputValue("Diorama Size") === "8x8";
  var plains = Generator.getSelectInputValue("Biome") === "Plains";
  var desert = Generator.getSelectInputValue("Biome") === "Desert";
  var gravelm = Generator.getSelectInputValue("Biome") === "Gravel Mountain";
  Generator.getSelectInputValue("Biome") === "Badlands";
  Generator.getSelectInputValue("Biome") === "Snow Plains";
  Generator.getSelectInputValue("Biome") === "Nether Wastes";
  Generator.getSelectInputValue("Biome") === "Soulsand walley";
  Generator.getSelectInputValue("Biome") === "Crimson Forest";
  Generator.getSelectInputValue("Biome") === "Warped Forest";
  Generator.getSelectInputValue("Biome") === "End";
  Generator.getSelectInputValue("Biome") === "Basalt Deltas";
  var dioramaheightvalue = [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ];
  Generator.usePage("Planing");
  var dioramablockname = [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1"
  ];
  var dioramablock1 = [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1"
  ];
  var dioramablock2 = [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1"
  ];
  var dioramablock3 = [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1"
  ];
  var dioramablock4 = [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1"
  ];
  var dioramablock5 = [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1"
  ];
  var dioramablock6 = [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1"
  ];
  Generator.drawImage("Background", [
        0,
        0
      ]);
  for(var i = 1; i <= 64; ++i){
    var i1 = Caml_array.get(dioramaheightvalue, i);
    if (plains) {
      if (i1 === 1) {
        Caml_array.set(dioramablockname, i, "Grass");
        Caml_array.set(dioramablock1, i, "Grass");
      }
      if (i1 === 2) {
        Caml_array.set(dioramablockname, i, "Grass");
        Caml_array.set(dioramablock1, i, "Dirt");
        Caml_array.set(dioramablock2, i, "Grass");
      }
      if (i1 === 3) {
        Caml_array.set(dioramablockname, i, "Grass");
        Caml_array.set(dioramablock1, i, "Dirt");
        Caml_array.set(dioramablock2, i, "Dirt");
        Caml_array.set(dioramablock3, i, "Grass");
      }
      if (i1 === 4) {
        Caml_array.set(dioramablockname, i, "Grass");
        Caml_array.set(dioramablock1, i, "Stone");
        Caml_array.set(dioramablock2, i, "Dirt");
        Caml_array.set(dioramablock3, i, "Dirt");
        Caml_array.set(dioramablock4, i, "Grass");
      }
      if (i1 === 5) {
        Caml_array.set(dioramablockname, i, "Grass");
        Caml_array.set(dioramablock1, i, "Stone");
        Caml_array.set(dioramablock2, i, "Stone");
        Caml_array.set(dioramablock3, i, "Dirt");
        Caml_array.set(dioramablock4, i, "Dirt");
        Caml_array.set(dioramablock5, i, "Grass");
      }
      if (i1 === 6) {
        Caml_array.set(dioramablockname, i, "Grass");
        Caml_array.set(dioramablock1, i, "Stone");
        Caml_array.set(dioramablock2, i, "Stone");
        Caml_array.set(dioramablock3, i, "Stone");
        Caml_array.set(dioramablock4, i, "Dirt");
        Caml_array.set(dioramablock5, i, "Dirt");
        Caml_array.set(dioramablock6, i, "Grass");
      }
      if (desert) {
        if (i1 === 1) {
          Caml_array.set(dioramablockname, i, "Sand");
          Caml_array.set(dioramablock1, i, "Sand");
        }
        if (i1 === 2) {
          Caml_array.set(dioramablockname, i, "Sand");
          Caml_array.set(dioramablock1, i, "Sand");
          Caml_array.set(dioramablock2, i, "Sand");
        }
        if (i1 === 3) {
          Caml_array.set(dioramablockname, i, "Sand");
          Caml_array.set(dioramablock1, i, "Sand");
          Caml_array.set(dioramablock2, i, "Sand");
          Caml_array.set(dioramablock3, i, "Sand");
        }
        if (i1 === 4) {
          Caml_array.set(dioramablockname, i, "Sand");
          Caml_array.set(dioramablock1, i, "Sandstone");
          Caml_array.set(dioramablock2, i, "Sand");
          Caml_array.set(dioramablock3, i, "Sand");
          Caml_array.set(dioramablock4, i, "Sand");
        }
        if (i1 === 5) {
          Caml_array.set(dioramablockname, i, "Sand");
          Caml_array.set(dioramablock1, i, "Sandstone");
          Caml_array.set(dioramablock2, i, "Sandstone");
          Caml_array.set(dioramablock3, i, "Sand");
          Caml_array.set(dioramablock4, i, "Sand");
          Caml_array.set(dioramablock5, i, "Sand");
        }
        if (i1 === 6) {
          Caml_array.set(dioramablockname, i, "Sand");
          Caml_array.set(dioramablock1, i, "Sandstone");
          Caml_array.set(dioramablock2, i, "Sandstone");
          Caml_array.set(dioramablock3, i, "Sandstone");
          Caml_array.set(dioramablock4, i, "Sand");
          Caml_array.set(dioramablock5, i, "Sand");
          Caml_array.set(dioramablock6, i, "Sand");
        }
        if (gravelm) {
          if (i1 === 1) {
            Caml_array.set(dioramablockname, i, "Gravel");
            Caml_array.set(dioramablock1, i, "Gravel");
          }
          if (i1 === 2) {
            Caml_array.set(dioramablockname, i, "Gravel");
            Caml_array.set(dioramablock1, i, "Gravel");
            Caml_array.set(dioramablock2, i, "Gravel");
          }
          if (i1 === 3) {
            Caml_array.set(dioramablockname, i, "Gravel");
            Caml_array.set(dioramablock1, i, "Gravel");
            Caml_array.set(dioramablock2, i, "Gravel");
            Caml_array.set(dioramablock3, i, "Gravel");
          }
          if (i1 === 4) {
            Caml_array.set(dioramablockname, i, "Gravel");
            Caml_array.set(dioramablock1, i, "Stone");
            Caml_array.set(dioramablock2, i, "Gravel");
            Caml_array.set(dioramablock3, i, "Gravel");
            Caml_array.set(dioramablock4, i, "Gravel");
          }
          if (i1 === 5) {
            Caml_array.set(dioramablockname, i, "Gravel");
            Caml_array.set(dioramablock1, i, "Stone");
            Caml_array.set(dioramablock2, i, "Stone");
            Caml_array.set(dioramablock3, i, "Gravel");
            Caml_array.set(dioramablock4, i, "Gravel");
            Caml_array.set(dioramablock5, i, "Gravel");
          }
          if (i1 === 6) {
            Caml_array.set(dioramablockname, i, "Gravel");
            Caml_array.set(dioramablock1, i, "Stone");
            Caml_array.set(dioramablock2, i, "Stone");
            Caml_array.set(dioramablock3, i, "Stone");
            Caml_array.set(dioramablock4, i, "Gravel");
            Caml_array.set(dioramablock5, i, "Gravel");
            Caml_array.set(dioramablock6, i, "Gravel");
          }
          
        }
        
      }
      
    }
    
  }
  
}

var generator = {
  id: id,
  name: name,
  thumbnail: undefined,
  video: undefined,
  instructions: undefined,
  images: images,
  textures: textures,
  script: script
};

exports.requireImage = requireImage;
exports.requireTexture = requireTexture;
exports.id = id;
exports.name = name;
exports.images = images;
exports.textures = textures;
exports.script = script;
exports.generator = generator;
/* images Not a pure module */
