// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Generators = require("./generators/Generators.bs.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var GeneratorView = require("./builder/views/GeneratorView.bs.js");
var GeneratorSelect = require("./GeneratorSelect.bs.js");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.bs.js");

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useState(function () {
        
      });
  var setGeneratorDef = match[1];
  var generatorDef = match[0];
  React.useEffect((function () {
          var generatorDef = Generators.generators.find(function (generator) {
                return generator.id === url.hash;
              });
          var generatorDef$1 = generatorDef === undefined ? undefined : Caml_option.some(generatorDef);
          Curry._1(setGeneratorDef, (function (param) {
                  return generatorDef$1;
                }));
          
        }), [url.hash]);
  var onGeneratorChange = function (generatorId) {
    if (generatorId !== undefined) {
      return RescriptReactRouter.push("/#" + generatorId);
    } else {
      return RescriptReactRouter.push("/");
    }
  };
  return React.createElement("div", {
              className: "p-4 pb-64"
            }, React.createElement("div", {
                  className: "pb-8"
                }, React.createElement(GeneratorSelect.make, {
                      onChange: onGeneratorChange,
                      value: url.hash
                    })), generatorDef !== undefined ? React.createElement(GeneratorView.make, {
                    generatorDef: generatorDef
                  }) : null);
}

var make = App;

var $$default = App;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
