// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Generator = require("../../builder/modules/Generator.bs.js");
var TextureMap = require("../TextureMap.bs.js");

function requireImage(id) {
  return require("./images/" + id + ".png");
}

function requireTexture(id) {
  return require("./textures/" + id + ".png");
}

var id = "minecraft-enderman-character";

var name = "Minecraft Enderman Character";

var thumbnail = {
  url: require("./thumbnail.jpg")
};

var imageIds = [
  "Background",
  "Labels",
  "Folds"
];

function toImageDef(id) {
  return {
          id: id,
          url: requireImage(id)
        };
}

var images = imageIds.map(toImageDef);

var textures = [{
    id: "Skin",
    url: requireTexture("Steve"),
    standardWidth: 64,
    standardHeight: 64
  }];

var steve = TextureMap.MinecraftCharacterLegacy.steve;

function script(param) {
  Generator.defineTextureInput("Skin", {
        standardWidth: 64,
        standardHeight: 64,
        choices: []
      });
  Generator.defineBooleanInput("Show Folds", true);
  Generator.defineBooleanInput("Show Labels", true);
  var showLabels = Generator.getBooleanInputValue("Show Labels");
  var showFolds = Generator.getBooleanInputValue("Show Folds");
  Generator.drawImage("Background", [
        0,
        0
      ]);
  Generator.drawTextureLegacy("Skin", steve.base.head.right, {
        x: 74,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.head.front, {
        x: 138,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.head.left, {
        x: 202,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.head.back, {
        x: 266,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.head.top, {
        x: 138,
        y: 25,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.head.bottom, {
        x: 138,
        y: 153,
        w: 64,
        h: 64
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.head.right, {
        x: 74,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.head.front, {
        x: 138,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.head.left, {
        x: 202,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.head.back, {
        x: 266,
        y: 89,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.head.top, {
        x: 138,
        y: 25,
        w: 64,
        h: 64
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.head.bottom, {
        x: 138,
        y: 153,
        w: 64,
        h: 64
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.body.right, {
        x: 268,
        y: 233,
        w: 32,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.body.front, {
        x: 300,
        y: 233,
        w: 64,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.body.left, {
        x: 364,
        y: 233,
        w: 32,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.body.back, {
        x: 396,
        y: 233,
        w: 64,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.body.top, {
        x: 300,
        y: 201,
        w: 64,
        h: 32
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.body.bottom, {
        x: 300,
        y: 329,
        w: 64,
        h: 32
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.body.right, {
        x: 268,
        y: 233,
        w: 32,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.body.front, {
        x: 300,
        y: 233,
        w: 64,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.body.left, {
        x: 364,
        y: 233,
        w: 32,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.body.back, {
        x: 396,
        y: 233,
        w: 64,
        h: 96
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.body.top, {
        x: 300,
        y: 201,
        w: 64,
        h: 32
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.body.bottom, {
        x: 300,
        y: 329,
        w: 64,
        h: 32
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightArm.right, {
        x: 96,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightArm.front, {
        x: 112,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightArm.left, {
        x: 128,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightArm.back, {
        x: 144,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightArm.top, {
        x: 112,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightArm.bottom, {
        x: 112,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightArm.right, {
        x: 96,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightArm.front, {
        x: 112,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightArm.left, {
        x: 128,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightArm.back, {
        x: 144,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightArm.top, {
        x: 112,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightArm.bottom, {
        x: 112,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftArm.right, {
        x: 190,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftArm.front, {
        x: 206,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftArm.left, {
        x: 222,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftArm.back, {
        x: 174,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftArm.top, {
        x: 206,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftArm.bottom, {
        x: 206,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftArm.right, {
        x: 190,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftArm.front, {
        x: 206,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftArm.front, {
        x: 222,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftArm.back, {
        x: 174,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftArm.top, {
        x: 206,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftArm.bottom, {
        x: 206,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightLeg.right, {
        x: 276,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightLeg.front, {
        x: 292,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightLeg.left, {
        x: 308,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightLeg.back, {
        x: 324,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightLeg.top, {
        x: 292,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.rightLeg.bottom, {
        x: 292,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightLeg.right, {
        x: 276,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightLeg.front, {
        x: 292,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightLeg.left, {
        x: 308,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightLeg.back, {
        x: 324,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightLeg.top, {
        x: 292,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.rightLeg.bottom, {
        x: 292,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftLeg.right, {
        x: 369,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftLeg.front, {
        x: 385,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftLeg.left, {
        x: 401,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftLeg.back, {
        x: 353,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftLeg.top, {
        x: 385,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.base.leftLeg.bottom, {
        x: 385,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftLeg.right, {
        x: 369,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftLeg.front, {
        x: 385,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftLeg.left, {
        x: 401,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftLeg.back, {
        x: 353,
        y: 400,
        w: 16,
        h: 238
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftLeg.top, {
        x: 385,
        y: 384,
        w: 16,
        h: 16
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Skin", steve.overlay.leftLeg.bottom, {
        x: 385,
        y: 638,
        w: 16,
        h: 16
      }, "Vertical", undefined, undefined, undefined);
  if (showFolds) {
    Generator.drawImage("Folds", [
          0,
          0
        ]);
  }
  if (showLabels) {
    return Generator.drawImage("Labels", [
                0,
                0
              ]);
  }
  
}

var generator_thumbnail = thumbnail;

var generator = {
  id: id,
  name: name,
  thumbnail: generator_thumbnail,
  video: undefined,
  instructions: undefined,
  images: images,
  textures: textures,
  script: script
};

exports.requireImage = requireImage;
exports.requireTexture = requireTexture;
exports.id = id;
exports.name = name;
exports.thumbnail = thumbnail;
exports.imageIds = imageIds;
exports.toImageDef = toImageDef;
exports.images = images;
exports.textures = textures;
exports.steve = steve;
exports.script = script;
exports.generator = generator;
/* thumbnail Not a pure module */
